version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 8000:8000
  backend:
    build: ./backend
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ttt_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080